title: Gyumin's Blog About Programming
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
  Gyumin Kim from Korea. All my notes about programming, especially WEB!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gyumin Kim # add your name
author-img: thread-crop.jpg # add your photo
about-author: Current bachelor student at INU. Getting ready to become a web application developer. # add description
social-twitter: / # add your Twitter handle
social-facebook: kmmguumnn # add your Facebook handle
social-github: gyumin-kim # add your Github handle
social-linkedin: gyumin-kim # add your Linkedin handle
social-email: starkying@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
